DELETE FROM currencies;
INSERT INTO currencies (id, display_name, display_name_locales, symbol)
VALUES
  ('USD', 'United States Dollar', '{"ru": "Доллар США", "en": "United States Dollar", "he": "דולר אמריקאי"}'::jsonb, '$'),
  ('EUR', 'Euro', '{"ru": "Евро", "en": "Euro", "he": "אירו"}'::jsonb, '€'),
  ('GBP', 'British Pound', '{"ru": "Британский фунт", "en": "British Pound", "he": "פאונד בריטי"}'::jsonb, '£'),
  ('ILS', 'New Israeli Shekel', '{"ru": "Новый израильский шекель", "en": "New Israeli Shekel", "he": "שקל חדש"}'::jsonb, '₪'),
  ('RUB', 'Russian Ruble', '{"ru": "Российский рубль", "en": "Russian Ruble", "he": "רובל רוסי"}'::jsonb, '₽'),
  ('JPY', 'Japanese Yen', '{"ru": "Японская иена", "en": "Japanese Yen", "he": "ין יפני"}'::jsonb, '¥'),
  ('CNY', 'Chinese Yuan', '{"ru": "Китайский юань", "en": "Chinese Yuan", "he": "יואן סיני"}'::jsonb, '¥'),
  ('AUD', 'Australian Dollar', '{"ru": "Австралийский доллар", "en": "Australian Dollar", "he": "דולר אוסטרלי"}'::jsonb, 'A$'),
  ('CAD', 'Canadian Dollar', '{"ru": "Канадский доллар", "en": "Canadian Dollar", "he": "דולר קנדי"}'::jsonb, 'C$'),
  ('CHF', 'Swiss Franc', '{"ru": "Швейцарский франк", "en": "Swiss Franc", "he": "פרנק שווייצרי"}'::jsonb, '₣'),
  ('SEK', 'Swedish Krona', '{"ru": "Шведская крона", "en": "Swedish Krona", "he": "קרונה שוודית"}'::jsonb, 'kr'),
  ('NOK', 'Norwegian Krone', '{"ru": "Норвежская крона", "en": "Norwegian Krone", "he": "קרונה נורווגית"}'::jsonb, 'kr'),
  ('DKK', 'Danish Krone', '{"ru": "Датская крона", "en": "Danish Krone", "he": "קרונה דנית"}'::jsonb, 'kr'),
  ('INR', 'Indian Rupee', '{"ru": "Индийская рупия", "en": "Indian Rupee", "he": "רופי הודי"}'::jsonb, '₹'),
  ('KRW', 'South Korean Won', '{"ru": "Южнокорейская вона", "en": "South Korean Won", "he": "ון קוריאני דרום"}'::jsonb, '₩'),
  ('MXN', 'Mexican Peso', '{"ru": "Мексиканское песо", "en": "Mexican Peso", "he": "פזו מקסיקני"}'::jsonb, '$'),
  ('ZAR', 'South African Rand', '{"ru": "Южноафриканский рэнд", "en": "South African Rand", "he": "רנד דרום אפריקאי"}'::jsonb, 'R'),
  ('AED', 'United Arab Emirates Dirham', '{"ru": "Дирхам ОАЭ", "en": "United Arab Emirates Dirham", "he": "דירהם של איחוד האמירויות"}'::jsonb, 'د.إ'),
  ('AFN', 'Afghan Afghani', '{"ru": "Афгани", "en": "Afghan Afghani", "he": "אפגני"}'::jsonb, '؋'),
  ('ALL', 'Albanian Lek', '{"ru": "Албанский лек", "en": "Albanian Lek", "he": "לק אלבני"}'::jsonb, 'L'),
  ('AMD', 'Armenian Dram', '{"ru": "Армянский драм", "en": "Armenian Dram", "he": "דראם ארמני"}'::jsonb, 'դր'),
  ('ANG', 'Netherlands Antillean Guilder', '{"ru": "Гульден Нидерландских Антильских островов", "en": "Netherlands Antillean Guilder", "he": "גילדר אנטיליים הולנדיים"}'::jsonb, 'ƒ'),
  ('AOA', 'Angolan Kwanza', '{"ru": "Ангольская кванза", "en": "Angolan Kwanza", "he": "קואנזה אנגולאי"}'::jsonb, 'Kz'),
  ('ARS', 'Argentine Peso', '{"ru": "Аргентинское песо", "en": "Argentine Peso", "he": "פזו ארגנטינאי"}'::jsonb, '$'),
  ('AWG', 'Aruban Florin', '{"ru": "Арубский флорин", "en": "Aruban Florin", "he": "פלורין ארובה"}'::jsonb, 'ƒ'),
  ('AZN', 'Azerbaijani Manat', '{"ru": "Азербайджанский манат", "en": "Azerbaijani Manat", "he": "מנאטן אזרי"}'::jsonb, '₼'),
  ('BBD', 'Barbadian Dollar', '{"ru": "Барбадосский доллар", "en": "Barbadian Dollar", "he": "דולר ברבדוס"}'::jsonb, '$'),
  ('BDT', 'Bangladeshi Taka', '{"ru": "Бангладешская така", "en": "Bangladeshi Taka", "he": "טאקה בנגלדשי"}'::jsonb, '৳'),
  ('BGN', 'Bulgarian Lev', '{"ru": "Болгарский лев", "en": "Bulgarian Lev", "he": "לב בולגרי"}'::jsonb, 'лв'),
  ('BHD', 'Bahraini Dinar', '{"ru": "Бахрейнский динар", "en": "Bahraini Dinar", "he": "דינר בחרייני"}'::jsonb, '.د.ب'),
  ('BIF', 'Burundian Franc', '{"ru": "Бурундийский франк", "en": "Burundian Franc", "he": "פרנק בורונדי"}'::jsonb, 'FBu'),
  ('BMD', 'Bermudian Dollar', '{"ru": "Бермудский доллар", "en": "Bermudian Dollar", "he": "דולר ברמודה"}'::jsonb, '$'),
  ('BND', 'Brunei Dollar', '{"ru": "Брунейский доллар", "en": "Brunei Dollar", "he": "דולר ברוניי"}'::jsonb, '$'),
  ('BOB', 'Bolivian Boliviano', '{"ru": "Боливийский боливиано", "en": "Bolivian Boliviano", "he": "בוליביאנו בוליביאני"}'::jsonb, 'Bs'),
  ('BRL', 'Brazilian Real', '{"ru": "Бразильский реал", "en": "Brazilian Real", "he": "ריאל ברזילאי"}'::jsonb, 'R$'),
  ('BSD', 'Bahamian Dollar', '{"ru": "Багамский доллар", "en": "Bahamian Dollar", "he": "דולר בהאמה"}'::jsonb, '$');
